sudo: false
language: go
go:
  - 1.7
  - 1.8
install:
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/tools/cmd/gosimple
  - go get honnef.co/go/tools/cmd/staticcheck
  - go get honnef.co/go/tools/cmd/unused
  - go get github.com/chzyer/readline
before_script:
  - (! gofmt -s -d . | grep '^')
  - go vet ./...
  - golint -set_exit_status ./...
  - staticcheck
  - unused
